### PR TITLE
config layout re-design & impl of action controller in config & wheel…

### PR DESCRIPTION
**Pull request by hosseinamin**
… mode impl +bugfix #160 #121

- Re-design of config layout

In new design config is separated in four parts. In desktop mode layout has tabs on left
side, By clicking on a section It's content will appear at center. In mobile mode section
do appear like pages that user can navigate in and out of them by back button at top.

- Config Action Controller implementation

Config of keys that trigger actions have re-implemented to support modifying multiple keys
that can trigger a specific action.

- Wheel Mode

In wheel mode user can use the wheel on their mouse/[touch(Not tested)] to navigate in the
tree. Wheel has two Axis each have two parameters. 1. Threshold, A number indicating
how much wheel should move to perform a single action. 2. Reverse, Which can be used to
reverse the action. For example instead of moving to next node it moves previous one.

### CODE REVIEW

**Comment by willwade** [comment]
Fab! One thing - the icon for the "Configure Actions" - Select item, Go back etc is currently three lines. What about using just arrows for these? So Select (Right arrow), Back (Left arrow), Next (Down arrow), Previous (Up arrow) ?

**Comment by willwade** [comment]
One thing I need to do is to test a) scroll functionality on iOS and b) test what happens when we move from current live version to this one - need to see if it will take the key actions across.. I'm assuming not

**Comment by willwade** [comment]
Might be something with Safari - but its not saving the key actions: https://www.dropbox.com/s/zecmmz1p4v13dzj/KeySaveBug.mov?dl=0

**Comment by hosseinamin** [comment]
> Fab! One thing - the icon for the "Configure Actions" - Select item, Go back etc is currently three lines. What about using just arrows for these? So Select (Right arrow), Back (Left arrow), Next (Down arrow), Previous (Up arrow) ?

Right. That make sense.

**Comment by hosseinamin** [comment]
> One thing I need to do is to test a) scroll functionality on iOS and b) test what happens when we move from current live version to this one - need to see if it will take the key actions across.. I'm assuming not

A: I have to test it in iOS too.
B: Yes. On update it will take registered keys from existing settings

**Comment by hosseinamin** [comment]
I s

> Might be something with Safari - but its not saving the key actions reliably: https://www.dropbox.com/s/zecmmz1p4v13dzj/KeySaveBug.mov?dl=0

This is probably a bug. I will fix it.

**Comment by willwade** [comment]
One tiny thing. The menu “Language” could be confused with locale in appearance. How about “Vocabulary” with a symbol like https://fontawesome.com/icons/comment-dots?style=regular ?

**Comment by hosseinamin** [comment]
Fixed

**Pull request merged**
