### PR TITLE
Impl of #88 & major change to dyn +bugfixes

### PR DESCRIPTION
**Pull request by hosseinamin**
Details are written in commit comments.

Example tree would be.

```
- Spell Branch<meta data-spell-branch  data-spell-update-dyn-onchange>
    - <meta data-dyn="spell-word-prediction" data-words-file="trees/sample01/sample-words.json" data-max-nodes="3" data-spell-finish>
    - <meta data-dyn="spell-letter-prediction" data-words-file="trees/sample01/sample-words.json">
    - Finish<meta data-spell-finish>
- 2
- 3
```

And `trees/sample01/sample-words.json` contains this.
```
{
  "words": [
    {"v":"because","w":2},
    {"v":"ready","w":1},
    {"v":"here","w":1},
    {"v":"there","w":1},
    {"v":"apple","w":1},
    {"v":"aid","w":1},
    {"v":"orange","w":1},
    {"v":"pickle","w":1}
  ]
}
```

Note. All words within words.json file should be lower case. It is possible to capitalize the first letter if it's needed...

### CODE REVIEW

**Comment by hosseinamin** [comment]
Note `meta data-dyn-insert-in` and `meta data-dyn-replace-node` has removed. https://github.com/AceCentre/pasco/pull/105/commits/6b8d1eae91a03a8ef0fad87162587dfe8bab30be

**Comment by hosseinamin** [comment]
@willwade You may also need to update deploy script of `app.pasco.chat`.

**Comment by willwade** [comment]
@hosseinamin - looking amazing! re: removing add/remove node - was there a conflict in this PR or removed on purpose?

**Comment by willwade** [comment]
Ignore my comment. Found your commit notes now!

**Comment by willwade** [comment]
No need to add T if not using it right now. I’ll give it a go later - great

**Pull request merged**
