### PR TITLE
message bar history impl & improvements & bugfixes

### PR DESCRIPTION
**Pull request by hosseinamin**
1. message bar implementation
2. at main change index.html body not-selectable but #tree is not-selectable
3. remove load_tree, instead install_tree at start, which helps to reduce
   complexity at start/stop process, and gather all initial manipulation at install_tree
4. introduce meta-auditory-main, It is now used at utterance of message bar.
   It will allow a node to be displayed with a specific text and then
   utterance will be auditory-main.

### CODE REVIEW

**Comment by willwade** [comment]
Cool! Anything I need to add to build script? https://deploy-preview-182--pasco-app.netlify.com

**Comment by willwade** [comment]
To be precise:


ReferenceError: Can't find variable: _tree_go_in
eval_config@https://deploy-preview-182--pasco-app.netlify.com/js/main.js:1892:30
https://deploy-preview-182--pasco-app.netlify.com/js/main.js:92:27
promiseReactionJob@[native code]

checkpoint: https://deploy-preview-182--pasco-app.netlify.com/js/main.js:94:37
promiseReactionJob@[native code]

**Comment by hosseinamin** [comment]
My mistake. Fixed

**Comment by willwade** [comment]
Couple of small tweaks. Is there a colour style for the Message bar? I wonder if we can do a seperate font size for message bar or would that get complicated? 

Also - re: "Utter message option in all branches"

Is this trying to do a message history? Its not really working for me. E.g. If I have it on - and say "Chat > Message history" it says "Chat, Message History". Is there something I'm not getting?

**Comment by hosseinamin** [comment]
> Couple of small questions!.
> 
>     1. Is there a colour style for the Message bar? (we have a user who needs it the same style as the main area - so I'm thinking we may need a line separating the two areas)
> 
>     2. I wonder if we can do a separate font size for message bar or would that get complicated?
>

Sure, Do you want fixed font-size? Or it should relatively smaller/larger.

> 
> Also - re: "Utter message option in all branches"
> 
>     1. Is this trying to do a message history? Its not really working for me. E.g. If I have it on - and say "Chat > Message history" it says "Chat, Message History". Is there something I'm not getting?

Well. I think. I didn't understand what you mean here, Can you elaborate, What it should do?

**Comment by willwade** [comment]
> > Couple of small questions!.
> > ```
> > 1. Is there a colour style for the Message bar? (we have a user who needs it the same style as the main area - so I'm thinking we may need a line separating the two areas)
> > 
> > 2. I wonder if we can do a separate font size for message bar or would that get complicated?
> > ```
> 
> Sure, Do you want fixed font-size? Or it should relatively smaller/larger.

I *think* relative

> 
> > Also - re: "Utter message option in all branches"
> > ```
> > 1. Is this trying to do a message history? Its not really working for me. E.g. If I have it on - and say "Chat > Message history" it says "Chat, Message History". Is there something I'm not getting?
> > ```
> 
> Well. I think. I didn't understand what you mean here, Can you elaborate, What it should do?

Ok - reading #119 I see whats going on now. I've written that badly..I think I know how to fix it - let me first demonstrate it with spelling.

So we spell something  "CAT" the person hits "Space" - it says it outloud - and the message bar clears. It shouldn't clear by default.  What we want is for "CAT SAT " etc.. to be in message bar. What we then need is a way for the user to *Read aloud* the whole message bar - and we would need an action to clear it. 

So to fix this; 
1. The Helper would create a two new elements "Read message bar" "Clear message bar". 
2. We also would have a meta-data action to manually allow someone to design a tree with these actions. 
3. In the helper - we also have a tick box - "Clear message bar on Speak - All messages" "Clear message bar on Speak - All except Spelling".

That make sense?

**Comment by hosseinamin** [comment]
I see, I think we need to separate spelling from normal selection.

In this code it is already separated to some extend. What if I implement message bar only for spelling.
We can extend It's use when it is needed?

**Comment by hosseinamin** [comment]
In fact we can skip these two new meta tags and keep it in existing ones in spell.

1. `spell-finish` will do same as read message bar, And it does clear message bar.
2. I think space is already reads the written word aloud.

**Comment by willwade** [comment]
Yes. That’s a good idea. Let’s keep it to spelling only for now.

**Comment by hosseinamin** [comment]
Now message bar is only for spelling.

**Comment by willwade** [comment]
Two small tweaks!
1. Can spell space read last word but NOT clear message bar 
2.  Can we make it themable so we can edit Color etc ?

**Comment by hosseinamin** [comment]
> Two small tweaks!
> 
>     1. Can spell space read last word but NOT clear message bar

At the moment spelling process does have its own speech at selection of space or any letter/word. And it does not clear message bar. What should I change now?

>     2. Can we make it themable so we can edit Color etc ?

Done

**Comment by willwade** [comment]
Fab. Apologies then. That should do for now.

**Comment by willwade** [comment]
@hosseinamin - Ok - Watch the video: https://www.dropbox.com/s/zrzbcom1n7kve1h/screen%20recording%202019-11-12%20at%2009.46.34.mov?dl=0 . Lets say I want to write "Happy as a cloud" (and then speak).. Currently it speaks and then clears after it says "Happy" (because Space appears to be clear it. Is there something wrong in my syntax? (this is the syntax of that video: https://raw.githubusercontent.com/AceCentre/pasco/master/html/trees/Adult_Starter/en-GB-Adult_Starter.md)

**Comment by hosseinamin** [comment]
The spell-word-prediction `dyn` has `data-spell-finish` attribute. Which means it will end it by uttering that word.
Please remove it and see if it does what you want. 
```
  <meta data-dyn="spell-word-prediction" data-words-file="trees/Spell_Prediction/bncfrequency.json" data-max-nodes="3" data-spell-finish>
```

**Comment by willwade** [comment]
Got it. Im an idiot (/need to document this better)

**Pull request merged**
