### PR TITLE
fix #134 & #100, override output to (headphone,builtinspeaker or default), +enhancement

### LINKED ISSUE #134: edit-config.html not found on iOS build
small bug I'm sure. Just a reminder!

### PR DESCRIPTION
**Pull request by hosseinamin**
edit-config.js contains a new button in cordova-ios for opening audio output volume + route control.

Three option for overriding output audio. Each does what it says. None will not override and listen to what user did ask at audio manager...

### CODE REVIEW

**Comment by hosseinamin** [comment]
Uploading ios build at TestFlight...

**Comment by hosseinamin** [comment]
At "Audio Output manager" one cannot control the state of it. Program cannot change it. User-interaction is required. I did add for someone to find it easily.

When bluetooth is connected. One should select bluetooth at "Audio Output manager" and set none on the voice for bluetooth speaker.

When bluetooth is not connected. As far as i can see, Effectively none and headphone will have the same outcome.

The problem with volume is weird, Can there be some other settings controlling it?

**Comment by willwade** [comment]
Got you. Ok - so I guess the answer is better documentation. I've got it working now reliably (Cue: Bluetooth, Main: Speaker) using your method. I'm wondering if there is better wording. I'm guessing we cant detect where the user is directing the audio in the Output manager and then auto-select None for them if they have something selected? (Or would that be a bad idea)

And maybe related - I realise this is out the scope of this PR - but is it possible to send Cue to one BT source and cue to another? I fear not :)

**Comment by hosseinamin** [comment]
> Got you. Ok - so I guess the answer is better documentation. I've got it working now reliably (Cue: Bluetooth, Main: Speaker) using your method. I'm wondering if there is better wording. I'm guessing we cant detect where the user is directing the audio in the Output manager and then auto-select None for them if they have something selected? (Or would that be a bad idea)

We can do this. 
 
> And maybe related - I realise this is out the scope of this PR - but is it possible to send Cue to one BT source and cue to another? I fear not :)

Yes. This is probably not possible. I should test it.

**Pull request merged**
