### PR TITLE
#164 & #147 + bugfix

### PR DESCRIPTION
**Pull request by hosseinamin**
stayinbranch for all helper + meta-endit

1. A new checkbox in helper section to toggle stay-in-branch for all nodes other than root node.
2. Use of `<meta data-select-utterance>` will result in a node to explicitly end the process and select that node.

 word prediction meta predict-after-n-chars #147 + bugfix

1. Adding meta `predict-after-n-chars="number"` to any predict dynnode will
   not show any suggestions until supplied number of chars has been selected.
2. Add missing code for flexbox layout change. '.children-wrp'.
3. A bugfix related to back helper option at beginning. It was showing the
   back option after suggestions (not at beginning).
   By using `tree_insert_node` instead of `tree_add_node`
   it accounts for dynnode's with empty elements when inserting a new node.

### CODE REVIEW

**Comment by willwade** [comment]
Great. Can you clarify..

We now have a global setting - Yay!
But what are all the meta-data tags..

<meta data-stay-in-branch> 
<meta data-endit>
<meta data-back-n-branch="1" data-back-n-branch-notify>

Are these right? Any others? I just want to make sure we aren't replicating something here - or clashing with anything.

Otherwise seems to work great :)

**Comment by hosseinamin** [comment]
> Great. Can you clarify..
> 
> We now have a global setting - Yay!
I'm not sure what do you mean here.
> But what are all the meta-data tags..
> 
> Are these right? Any others? I just want to make sure we aren't replicating something here - or clashing with anything.

Two meta data is added in this commit.

1. `<meta data-endit>` This meta is useful in case you want to explicitly select a leaf node while stayinbranch is selected on one of Its parent. It acts like `data-spell-finish`.
2. For two `<meta data-dyn="...` prediction that we have. If one adds `data-predict-after-n-chars="3"`. It won't show any prediction until 3 characters has selected.

> 
> Otherwise seems to work great :)

**Comment by willwade** [comment]
“I’m not sure what do you mean” - just saying it looks good!

So do you think we should deprecate data-spell-finish?  Just worried we are adding loads of data- functions that do the thing. Or do they work differently?

**Comment by hosseinamin** [comment]
> “I’m not sure what do you mean” - just saying it looks good!
> 
> So do you think we should deprecate data-spell-finish? Just worried we are adding loads of data- functions that do the thing. Or do they work differently?

Yeah. We can do that. I wasn't able to come up with a good name for `data-endit`. `data-finish` is confusing. Yeah. Maybe deprecating spell-finish is good.

**Comment by willwade** [comment]
data-exit-branch ?

**Comment by hosseinamin** [comment]
I'm not sure. The process doesn't have a name. Let's call it communication session. Then maybe. `data-end-session` would be good.

**Comment by hosseinamin** [comment]
Or communication attempt, How about `data-select`?

**Comment by hosseinamin** [comment]
how about `select-utterance`?

**Comment by hosseinamin** [comment]
`data-endit` will actually select that node. Meaning cue voice is going get uttered. So In my opinion.  `select-utterance` is best. And maybe we have to keep data-spell-finish.

**Comment by willwade** [comment]
Ok. Agreed :)

**Comment by willwade** [comment]
Just realised my comment had the meta data commands hidden..

So to clarify, we have

`<meta data-stay-in-branch>`

`<meta data-back-n-branch="1" data-back-n-branch-notify>`

`<meta data-select-utterance>`

Is there any others?

**Comment by hosseinamin** [comment]
> Just realised my comment had the meta data commands hidden..
> 
> So to clarify, we have
> 
> `<meta data-stay-in-branch>`
> 
> `<meta data-back-n-branch="1" data-back-n-branch-notify>`
> 
> `<meta data-select-utterance>`
> 
> Is there any others (related to staying in a branch)?

Right, I think so.

**Comment by willwade** [comment]
Think found some others..

` data-onselect-continue-in-branch data-onselect-continue-concat`

is that `data-onselect-continue-in-branch` different?

**Comment by hosseinamin** [comment]
> Think found some others..
> 
> ` data-onselect-continue-in-branch data-onselect-continue-concat`
> 
> is that `data-onselect-continue-in-branch` different?

Are these actually implemented? I looked at `main.js` I can't find them.

**Comment by willwade** [comment]
> > Think found some others..
> > ` data-onselect-continue-in-branch data-onselect-continue-concat`
> > is that `data-onselect-continue-in-branch` different?
> 
> Are these actually implemented? I looked at `main.js` I can't find them.

Maybe not! Found in: https://raw.githubusercontent.com/AceCentre/pasco/master/html/trees/Spell_by_blocks_in_frequency/en-GB-Spell_by_blocks_in_frequency.md

**Comment by hosseinamin** [comment]
I see, I did replace them with `data-spell....`.

**Comment by willwade** [comment]
Can you do me a favour - on this PR - can you update those html/trees and fix those clearly not working data commands? (Only I'll forget in a days time..!)

**Pull request merged**
