### PR TITLE
1.5 Visual tweaks Release

### PR DESCRIPTION
**Pull request by hosseinamin**

### CODE REVIEW

**Comment by willwade** [comment]
I’m not sure which issue this is under but see this bug. https://www.dropbox.com/s/ytqic14o400efjc/Video%2002-04-2020%2C%2022%2045%2040.mp4?dl=0 - notice how it snaps back on spelling and then back to that node.

**Comment by hosseinamin** [comment]
snap back issue fixed

**Comment by willwade** [comment]
Great. Looking good. It’s not a major one but did you mean to leave a space at the bottom? I notice this when I first run it but then disappeared when I went back to the app https://www.dropbox.com/s/75z20pfucwkbfb1/Photo%2004-04-2020%2C%2016%2027%2029.jpg?dl=0

**Comment by willwade** [comment]
Another minor bug. Do this

- turn message bar on
- start spelling a word 
- go to settings and turn on message bar
- hit play

And input freezes 
Restarting the app fixes it 

Maybe not that important

**Comment by hosseinamin** [comment]
> Another minor bug. Do this
> 
>     * turn message bar on
> 
>     * start spelling a word
> 
>     * go to settings and turn off message bar
> 
>     * hit play
> 
> 
> And input freezes
> Restarting the app fixes it
> 
> Doesn’t happen if not middle of spelling a word.
> 
> Maybe not that important

I don't get what you mean, Can you show me a video?

**Comment by hosseinamin** [comment]
> Great. Looking good. It’s not a major one but did you mean to leave a space at the bottom? I notice this when I first run it but then disappeared when I went back to the app https://www.dropbox.com/s/75z20pfucwkbfb1/Photo%2004-04-2020%2C%2016%2027%2029.jpg?dl=0

Fixed.

**Comment by willwade** [comment]
> > Another minor bug. Do this
> 
> > 
> 
> >     * turn message bar on
> 
> > 
> 
> >     * start spelling a word
> 
> > 
> 
> >     * go to settings and turn off message bar
> 
> > 
> 
> >     * hit play
> 
> > 
> 
> > 
> 
> > And input freezes
> 
> > Restarting the app fixes it
> 
> > 
> 
> > Doesn’t happen if not middle of spelling a word.
> 
> > 
> 
> > Maybe not that important
> 
> 
> 
> I don't get what you mean, Can you show me a video?

Sure. https://www.dropbox.com/s/0pu32num2wtlkoo/Video%2004-04-2020%2C%2019%2046%2021.mp4?dl=0

**Comment by hosseinamin** [comment]
>Sure. https://www.dropbox.com/s/0pu32num2wtlkoo/Video%2004-04-2020%2C%2019%2046%2021.mp4?dl=0

Other than the issue with displaying the tree in full-height. I didn't see any other issue.

**Comment by willwade** [comment]
Watch the very end. The arrow keys become unresponsive.

**Comment by hosseinamin** [comment]
This is odd, Can you try it again? (last fix may have fixed this issue as well)
I'm not sure why this is happening. If there was an error. It should not work after a restart.

**Comment by hosseinamin** [comment]
Let me try it on simulator. I think I did (was ok), Not sure.

**Comment by hosseinamin** [comment]
Sorry, full-height issue is not fixed. I thought I fixed it

**Comment by willwade** [comment]
Fab. This is great. Thanks for everything

**Pull request merged**
