### PR TITLE
[WIP] Webpack Migration

### PR DESCRIPTION
**Pull request by gavinhenderson**
# Pages Migrated
- [x] Intro
- [x] Help
- [ ] Edit Config (in progress)
- [ ] Quick Setup
- [ ] Main (index)

# New NPM scripts:
`webpack:dev` - Runs webpack-dev-server and opens app in the browser
`webpack:build` - Builds the webpack app to the `dist` folder
`webpack:cordova-dev` - Opens a simulator and runs the webpack app in it (includes hot reloading)
`webpack:cordova-build` - Builds the webpack app into the cordova folder

`test` - Runs jest tests
`test:watch` - Runs the tests in watch mode
`test:coverage` - Outputs the test coverage

# Config

There is a `webpack` folder that contains all the config files for webpack. `HtmlWebpackPlugin` is used to copy the HTML pages into the build and then we give each file one chunk. It might make sense eventually to have a main chunk and include that in all pages.

# How to help

Start migrating a page and submit a PR. I will make sure to keep this branch up to date with master, so if you make improvements to the master ill make sure they end up on this branch.

Another great way to contribute would be to add some tests! 👍 

Any questions or comments dont hesitate to reach out :)

### CODE REVIEW

**Comment by gavinhenderson** [comment]
Hey @willwade and @hosseinamin I was wondering if you could give me a hand with a few quick questions. Why is there a different help file for 'es-ES' locale but no other locale, and why is it in english? Is this something we still need?

Also how much of a focus is internationalisation of the project? It seems to add a lot of complexity to the codebase and if no one needs it I would suggest we leave it out of the migration?

**Comment by willwade** [comment]
Great question. That help shouldn’t have been committed. It what led to a general discussion that we may want to rethink how we do the locale stuff - at least for the help pages. L10n is fairly important in that we have had to support people who are not English speaking - as caters or the direct user. The whole bi lingual thing makes it pretty unique.  But saying that - it’s probably not being used that much at this stage. If it’s hellish then I can go with leaving it out but would be good to think how it should be done. See also https://github.com/AceCentre/pasco/issues/102 and https://github.com/AceCentre/pasco/issues/104

**Comment by gavinhenderson** [comment]
@willwade Perfect, ill pull that out :) Im happy to leave the l10n stuff in, just wanted to make sure that it had some value and sounds like it has lots!

**Comment by gavinhenderson** [comment]
Going to close this.

It was to ambitious. Whatever we do we will need to do it incrementally and not big bang. The code is still accessible for inspiration

**Pull request closed without merging**
